# Generated by Django 5.2.3 on 2025-06-24 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, default='Без темы', help_text='Введите тему письма', max_length=50, null=True, verbose_name='Тема письма')),
                ('text', models.TextField(help_text='Напишите письмо', verbose_name='Тело письма')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
                'ordering': ['subject'],
            },
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_sending', models.DateTimeField(help_text='Введите дату и время начала рассылки', verbose_name='Начало рассылки')),
                ('end_sending', models.DateTimeField(help_text='Введите дату и время окончания рассылки', verbose_name='Окончание рассылки')),
                ('status', models.CharField(choices=[('Создана', 'Создана'), ('Запущена', 'Запущена'), ('Завершена', 'Завершена')], default='Создана', help_text='Статус рассылки', max_length=9, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
                'ordering': ['status', 'end_sending', 'start_sending'],
            },
        ),
        migrations.CreateModel(
            name='NewsletterAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_attempt', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время попытки рассылки')),
                ('status', models.CharField(choices=[('Успешно', 'Успешно'), ('Не успешно', 'Не успешно')], default='Не успешно', help_text='Статус попытки рассылки', max_length=10, verbose_name='Статус')),
                ('answer', models.TextField(verbose_name='Ответ почтового сервера')),
            ],
        ),
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(help_text='Введите адрес электронной почты', max_length=100, unique=True, verbose_name='email')),
                ('full_name', models.CharField(help_text='Введите Ваше ФИО в именительном падеже', max_length=100, verbose_name='ФИО')),
                ('message', models.TextField(blank=True, help_text='Добавьте комментарий', null=True, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Получатель',
                'verbose_name_plural': 'Получатели',
                'ordering': ['full_name', 'email'],
            },
        ),
    ]
