# Generated by Django 5.2.3 on 2025-06-27 11:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, default='Без темы', help_text='Введите тему письма', max_length=50, null=True, verbose_name='Тема письма')),
                ('text', models.TextField(help_text='Напишите письмо', verbose_name='Тело письма')),
                ('owner', models.ForeignKey(blank=True, help_text='Укажите владельца', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_owner', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
                'ordering': ['subject'],
            },
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_sending', models.DateTimeField(help_text='Введите дату и время начала рассылки', verbose_name='Начало рассылки')),
                ('end_sending', models.DateTimeField(help_text='Введите дату и время окончания рассылки', verbose_name='Окончание рассылки')),
                ('status', models.CharField(choices=[('Создана', 'Создана'), ('Запущена', 'Запущена'), ('Завершена', 'Завершена')], default='Создана', help_text='Статус рассылки', max_length=9, verbose_name='Статус')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='newsletters.message', verbose_name='Письмо')),
                ('owner', models.ForeignKey(blank=True, help_text='Укажите владельца', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='newsletter_owner', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
                'ordering': ['status', 'end_sending', 'start_sending'],
            },
        ),
        migrations.CreateModel(
            name='NewsletterAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_attempt', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время попытки рассылки')),
                ('status', models.CharField(choices=[('Успешно', 'Успешно'), ('Не успешно', 'Не успешно')], default='Не успешно', help_text='Статус попытки рассылки', max_length=10, verbose_name='Статус')),
                ('answer', models.TextField(verbose_name='Ответ почтового сервера')),
                ('newsletter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='newsletters.newsletter', verbose_name='Рассылка')),
            ],
            options={
                'verbose_name': 'Попытка рассылки',
                'verbose_name_plural': 'Попытки рассылок',
                'ordering': ['status', 'date_attempt'],
            },
        ),
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(help_text='Введите адрес электронной почты', max_length=100, unique=True, verbose_name='Электронная почта')),
                ('full_name', models.CharField(help_text='Введите Ваше ФИО в именительном падеже', max_length=100, verbose_name='ФИО')),
                ('message', models.TextField(blank=True, help_text='Добавьте комментарий', null=True, verbose_name='Комментарий')),
                ('owner', models.ForeignKey(blank=True, help_text='Укажите владельца', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipient_owner', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Получатель',
                'verbose_name_plural': 'Получатели',
                'ordering': ['full_name', 'email'],
            },
        ),
        migrations.AddField(
            model_name='newsletter',
            name='recipient',
            field=models.ManyToManyField(related_name='recipients', to='newsletters.recipient', verbose_name='Получатели'),
        ),
    ]
